services:
  backend:
    image: "dax0s/bonus-task-2023-spring-backend"
    container_name: "backend"
    ports:
      - "8080:8080"
    networks:
      - app_network
  
  frontend:
    image: "dax0s/bonus-task-2023-spring-frontend"
    container_name: "frontend"
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network: